x-app-env: &app-env
  ANALYTICS_ENABLED: ${ANALYTICS_ENABLED:-true}
  ANALYTICS_IP_SALT: ${ANALYTICS_IP_SALT:-change-me}
  APP_VERSION: ${APP_VERSION:-0.1.0}
  VITE_ANALYTICS_ENABLED: ${VITE_ANALYTICS_ENABLED:-true}

services:
  postgres:
    image: postgres:16
    container_name: book-snippets-postgres
    env_file: .env
    environment:
      <<: *app-env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db/init:/docker-entrypoint-initdb.d:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 10

  pgadmin:
    image: dpage/pgadmin4:8
    container_name: book-snippets-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "8080:80"
    depends_on:
      - postgres

volumes:
  postgres_data: